Repository RAF-SI-2023/Banka-2-Backend, pull requests merged in 2024-05, with the labels that each got.

#267 uradjeni buy/sell trading jobs
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/OrderActionType.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/SecuritiesOwnershipRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/SecuritiesOwnershipServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
Labels: size/L, lgtm, approved

#268 zapoceta logika za marzne racune i transakcije
  BankService/src/main/java/rs/edu/raf/BankService/configuration/RestTemplateConfig.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/MarginsAccountController.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/BankStockDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/MarginsAccountDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/MarginsTransactionDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/MarginsAccount.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/MarginsTransaction.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/TransactionDirection.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/MarginsAccountMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/MarginsTransactionMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/MarginsAccountRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/MarginsTransactionRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/service/MarginsAccountService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/MarginsTransactionService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/OrderService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/MarginsAccountServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/MarginsTransactionServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
  StockService/src/main/java/rs/edu/raf/StockService/controllers/BankServiceCommunicationController.java
  StockService/src/main/java/rs/edu/raf/StockService/data/dto/BankStockDto.java
  StockService/src/main/java/rs/edu/raf/StockService/services/facade/BankStockFacadeImpl.java
Labels: size/L, lgtm, approved

#269 otc +orderi
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  BankService/src/main/java/rs/edu/raf/BankService/configuration/SpringSecurityConfig.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/OrderController.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/SecuritiesOwnershipsController.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/TransferTransactionController.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/ContractDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/GenericTransactionDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/SecuritiesOwnershipDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/SecuritiesTransactionDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/transactions/SecuritiesTransaction.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/ContractStatus.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/ContractType.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/ListingType.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/SecuritiesOwnershipMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/TransactionMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/SecuritiesOwnershipRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/service/SecuritiesOwnershipService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/StockService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/TransactionService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/SecuritiesOwnershipServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/StockServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
  BankService/src/main/resources/application-dev.properties
  BankService/src/main/resources/application-prod.properties
  BankService/src/main/resources/application-test.properties
  IAMService/src/main/java/rs/edu/raf/IAMService/controllers/CompanyController.java
  IAMService/src/main/java/rs/edu/raf/IAMService/repositories/CompanyRepository.java
  IAMService/src/main/java/rs/edu/raf/IAMService/services/CompanyService.java
  IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/CompanyServiceImpl.java
  OTCService/src/main/java/rs/edu/raf/OTCService/bootstrap/BootstrapData.java
  OTCService/src/main/java/rs/edu/raf/OTCService/controllers/ContractController.java
  OTCService/src/main/java/rs/edu/raf/OTCService/data/dto/ContractDto.java
  OTCService/src/main/java/rs/edu/raf/OTCService/data/dto/GenericTransactionDto.java
  OTCService/src/main/java/rs/edu/raf/OTCService/data/dto/OrderDto.java
  OTCService/src/main/java/rs/edu/raf/OTCService/data/entity/Contract.java
  OTCService/src/main/java/rs/edu/raf/OTCService/data/enums/ContractStatus.java
  OTCService/src/main/java/rs/edu/raf/OTCService/data/enums/ContractType.java
  OTCService/src/main/java/rs/edu/raf/OTCService/data/enums/ListingType.java
  OTCService/src/main/java/rs/edu/raf/OTCService/data/enums/OrderActionType.java
  OTCService/src/main/java/rs/edu/raf/OTCService/data/enums/OrderStatus.java
  OTCService/src/main/java/rs/edu/raf/OTCService/data/enums/TransactionStatus.java
  OTCService/src/main/java/rs/edu/raf/OTCService/data/enums/TransactionType.java
  OTCService/src/main/java/rs/edu/raf/OTCService/filters/JwtFilter.java
  OTCService/src/main/java/rs/edu/raf/OTCService/filters/principal/CustomUserPrincipal.java
  OTCService/src/main/java/rs/edu/raf/OTCService/mappers/ContractMapper.java
  OTCService/src/main/java/rs/edu/raf/OTCService/repositories/ContractRepository.java
  OTCService/src/main/java/rs/edu/raf/OTCService/service/BankService.java
  OTCService/src/main/java/rs/edu/raf/OTCService/service/ContractService.java
  OTCService/src/main/java/rs/edu/raf/OTCService/service/impl/BankServiceImpl.java
  OTCService/src/main/java/rs/edu/raf/OTCService/service/impl/ContractServiceImpl.java
  OTCService/src/main/java/rs/edu/raf/OTCService/util/SpringSecurityUtil.java
  OTCService/src/main/resources/application.properties
  StockService/src/main/java/rs/edu/raf/StockService/controllers/ExchangeController.java
  StockService/src/main/java/rs/edu/raf/StockService/services/StockService.java
  StockService/src/main/java/rs/edu/raf/StockService/services/impl/StockServiceImpl.java
Labels: lgtm, approved, size/XXL

#272 bugfixes
  BankService/src/main/java/rs/edu/raf/BankService/controller/SecuritiesOwnershipsController.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/OrderActionType.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/SecuritiesOwnershipRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/service/SecuritiesOwnershipService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/SecuritiesOwnershipServiceImpl.java
  OTCService/src/main/java/rs/edu/raf/OTCService/controllers/ContractController.java
  OTCService/src/main/java/rs/edu/raf/OTCService/service/impl/ContractServiceImpl.java
Labels: lgtm, approved, size/M

#270 Dodat bootstrap za Contracts i Securites Ownership
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  OTCService/src/main/java/rs/edu/raf/OTCService/bootstrap/BootstrapData.java
  OTCService/src/main/resources/application.properties
Labels: size/L, lgtm, approved

#273 Uradjena metoda za getovanje transakcija preko maila i njeni testovi
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/TransferTransactionController.java
  BankService/src/main/java/rs/edu/raf/BankService/service/TransactionService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/transaction/TransferTransactionE2ETests.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/CheckTransactionByEmailTest.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/transferTransaction/TransferService.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/transferTransaction/TrasnferController.java
  BankService/src/test/resources/features/integration/transaction-integration/check_transactions_by_email.feature
Labels: size/L, lgtm, approved

#274 Ispravljena maper za transakcija da pokazuje koji je tip transakcije
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/TransactionType.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/TransactionMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  IAMService/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapDevData.java
  IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/UserServiceImpl.java
Labels: size/L, lgtm, approved

#275 Uradjeni testovi za security ownership
  BankService/src/test/java/rs/edu/raf/BankService/e2e/securityOwnership/SecurityOwnershipControllerJwtConst.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/securityOwnership/SecurityOwnershipControllerSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/securityOwnership/SecurityOwnershipControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/securityOwnership/SecurityOwnershipControllerTestsConfig.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/securityOwnership/SecurityOwnershipsImplSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/securityOwnership/SecurityOwnershipsImplTests.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/securityOwnership/SecurityOwnershipsTestConfig.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/securitiesOwnerships/SecuritiesOwnershipsControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/securitiesOwnerships/SecuritiesOwnershipsServiceTests.java
  BankService/src/test/resources/features/e2e/securityOwnership/securityOwnershipFeatures.feature
  BankService/src/test/resources/features/integration/securitiesOwnership-integration/securitiesOwnershipFeatures.feature
Labels: size/XL, lgtm, approved

#277 Dodatne metode
  BankService/src/main/java/rs/edu/raf/BankService/controller/OrderController.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/AccountDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/BusinessAccountDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/DomesticCurrencyAccountDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/ForeignCurrencyAccountDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/Order.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/AccountMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/service/CashAccountService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CashAccountServiceImpl.java
  OTCService/src/main/java/rs/edu/raf/OTCService/controllers/ContractController.java
  OTCService/src/main/java/rs/edu/raf/OTCService/service/ContractService.java
  OTCService/src/main/java/rs/edu/raf/OTCService/service/impl/ContractServiceImpl.java
Labels: lgtm, approved, size/M

#280 test
  BankService/src/main/java/rs/edu/raf/BankService/controller/OrderController.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/AgentDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/BankStockDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/BusinessAccountDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/ForeignCurrencyHolderDto.java
Labels: lgtm, approved, size/XS

#281 bugifx
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
Labels: lgtm, approved, size/XS

#282 Sada getOrderById vraca OrderDto
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/OrderController.java
  BankService/src/main/java/rs/edu/raf/BankService/service/OrderService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
Labels: size/S, lgtm, approved

#283 Izmene
  BankService/src/main/java/rs/edu/raf/BankService/controller/OrderController.java
  IAMService/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapDevData.java
Labels: size/S, lgtm, approved

#284 Da sefe
  BankService/src/main/java/rs/edu/raf/BankService/controller/OrderController.java
Labels: size/S, lgtm, approved

#286 Dodat getDeniedOrders
  BankService/src/main/java/rs/edu/raf/BankService/controller/OrderController.java
Labels: lgtm, approved, size/XS

#289 Create build.yaml
  .prow/build.yaml
Labels: lgtm, approved, size/M

#290 approveOrder stavlja u izvrsavanje
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/ActiveTradingJob.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/ActiveTradingJobRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingJob.java
  BankService/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
Labels: size/L, lgtm, approved

#292 orderi->forex+transakcije
  bank-service/src/main/java/rs/edu/raf/BankService/controller/OrderTransactionController.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/ForexDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/repository/OrderTransactionRepository.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/OrderTransactionService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/OrderTransactionServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/StockServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
  docker-compose.yml
  stock-service/src/main/java/rs/edu/raf/StockService/controllers/ForexController.java
Labels: size/L, lgtm, approved

#293 Stavio default vrednosti za env varijable koje nisu definisane
  bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/IAMServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/StockServiceImpl.java
  bank-service/src/main/resources/application.properties
  iam-service/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapDevData.java
  otc-service/src/main/java/rs/edu/raf/OTCService/bootstrap/BootstrapData.java
  otc-service/src/main/java/rs/edu/raf/OTCService/service/impl/BankServiceImpl.java
Labels: lgtm, approved, size/M

#296 Dodati ispisi zbog testiranja na kubernetesu
  iam-service/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapDevData.java
Labels: lgtm, approved, size/M

#297 logging instead of printing
  iam-service/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapDevData.java
Labels: size/S, lgtm, approved

#298 Lazy to eager stratefgy
  iam-service/src/main/java/rs/edu/raf/IAMService/data/entites/Role.java
Labels: lgtm, approved, size/XS

#303 Revert "Obrisan config zxa hibernetes"
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/CurrencyExchangeServiceImpl.java
Labels: lgtm, approved, size/XS

#304 Revert "Hibernatte config"
  iam-service/src/main/java/rs/edu/raf/IAMService/configuration/HibernateConfig.java
Labels: size/S, lgtm, approved

#305 Update README.md
  README.md
Labels: lgtm, approved, size/XS

#306 Revert "Lazy to eager stratefgy"
  iam-service/src/main/java/rs/edu/raf/IAMService/data/entites/Role.java
Labels: lgtm, approved, size/XS

#308 Krive drine
  bank-service/src/main/java/rs/edu/raf/BankService/data/entities/transactions/TransferTransaction.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/CurrencyExchangeServiceImpl.java
  bank-service/src/test/java/rs/edu/raf/BankService/e2e/currencyExchange/CurrencyExchangeControllerTestSteps.java
  bank-service/src/test/java/rs/edu/raf/BankService/e2e/securityOwnership/SecurityOwnershipControllerSteps.java
  bank-service/src/test/java/rs/edu/raf/BankService/e2e/transaction/TransferTransactionE2ETests.java
  bank-service/src/test/java/rs/edu/raf/BankService/integration/securityOwnership/SecurityOwnershipsImplSteps.java
  bank-service/src/test/java/rs/edu/raf/BankService/integration/transactionservice/CheckTransactionByEmailTest.java
  bank-service/src/test/java/rs/edu/raf/BankService/integration/transactionservice/TransactionServiceIntegrationTest.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/securitiesOwnerships/SecuritiesOwnershipsServiceTests.java
  bank-service/src/test/resources/features/integration/securitiesOwnership-integration/securitiesOwnershipFeatures.feature
  iam-service/src/main/java/rs/edu/raf/IAMService/data/entites/Role.java
Labels: lgtm, approved, size/M

#309 odredenja prosirenja(porez,za profit,) +bugfix
  bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/OrderController.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/SecuritiesOwnershipDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/entities/SecuritiesOwnership.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/entities/transactions/OrderTransaction.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/SecuritiesOwnershipMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/StockServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
  stock-service/src/main/java/rs/edu/raf/StockService/controllers/OptionController.java
  stock-service/src/main/java/rs/edu/raf/StockService/data/dto/OptionDto.java
  stock-service/src/main/java/rs/edu/raf/StockService/services/OptionService.java
  stock-service/src/main/java/rs/edu/raf/StockService/services/impl/OptionServiceImpl.java
Labels: size/L, lgtm, approved

#317 Bugfixes 👍
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/FuturesContractDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/StockServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
  otc-service/src/main/java/rs/edu/raf/OTCService/controllers/ContractController.java
  otc-service/src/main/java/rs/edu/raf/OTCService/data/enums/TransactionType.java
  otc-service/src/main/java/rs/edu/raf/OTCService/service/impl/BankServiceImpl.java
  stock-service/src/main/java/rs/edu/raf/StockService/bootstrap/readers/FuturesContractCsvReader.java
  stock-service/src/main/java/rs/edu/raf/StockService/data/entities/FuturesContract.java
  stock-service/src/main/java/rs/edu/raf/StockService/mapper/FuturesContractMapper.java
  stock-service/src/main/resources/csvs/future_data.csv
  stock-service/src/test/java/rs/edu/raf/StockService/services/impl/FuturesContractImplTest.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/mapper/FuturesContractMapperTest.java
Labels: size/L, lgtm, approved

#310 Napravljena entitet BankTransferTransactionDetail
  bank-service/src/main/java/rs/edu/raf/BankService/controller/BankTransferTransactionDetailsController.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/CurrencyExchangeController.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/BankTransferTransactionDetailsDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/entities/exchangeCurrency/BankTransferTransactionDetails.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/BankTransferTransactionDetailsMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/repository/BankTransferTransactionDetailsRepository.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/BankTransferTransactionDetailsService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/BankTransferTransactionDetailsServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/CurrencyExchangeServiceImpl.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeServiceTests.java
  iam-service/src/main/resources/application-dev.properties
Labels: size/L, lgtm, approved

#321 Main
  README.md
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/CurrencyExchangeServiceImpl.java
Labels: lgtm, approved, size/XS

#323 Main
  otc-service/src/main/java/rs/edu/raf/OTCService/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/XS
