Repository RAF-SI-2023/Banka-2-Backend, pull requests merged in 2024-07, with the labels that each got.

#389 tst
  bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapTestData.java
  bank-service/src/test/java/rs/edu/raf/BankService/e2e/credit/CreditControllerTestSteps.java
  bank-service/src/test/java/rs/edu/raf/BankService/e2e/credit/CreditControllerTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/e2e/securityOwnership/SecurityOwnershipControllerSteps.java
  bank-service/src/test/java/rs/edu/raf/BankService/e2e/transaction/TransferTransactionE2ETests.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/ActionAgentProfitControllerTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/BankProfitControllerTest.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/BankTransferTransactionDetailsControllerTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/MarginsAccountServiceImplTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/MarginsTransactionControllerTest.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/MarginsTransactionServiceImplTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/OtcBankTransactionServiceImplTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/account/MarginsAccountControllerTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/mapper/AccountMapperTest.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/mapper/ActionAgentProfitMapperTest.java
  bank-service/src/test/resources/features/e2e/accountController/accountFeaturesController.feature
  bank-service/src/test/resources/features/e2e/cardController/cardFeaturesController.feature
  bank-service/src/test/resources/features/e2e/creditController/creditFeaturesE2E.feature
  bank-service/src/test/resources/features/integration/card-integration/cardFeatures.feature
  bank-service/src/test/resources/features/integration/credit-integration/creditFeatures.feature
  iam-service/src/test/resources/features/e2e/authcontroller/AuthController.feature
  otc-service/src/main/java/rs/edu/raf/OTCService/bootstrap/BootstrapData.java
  otc-service/src/main/java/rs/edu/raf/OTCService/controllers/ContractController.java
  otc-service/src/main/java/rs/edu/raf/OTCService/service/impl/ContractServiceImpl.java
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/buyingAndSellingOrders/BuyingAndSellingOrdersSteps.java
  otc-service/src/test/java/rs/edu/raf/OTCService/unit/controllers/BankOtcControllerTests.java
  otc-service/src/test/java/rs/edu/raf/OTCService/unit/controllers/ContractControllerImplTest.java
  otc-service/src/test/java/rs/edu/raf/OTCService/unit/mappers/ContractMapperTest.java
  otc-service/src/test/java/rs/edu/raf/OTCService/unit/services/ContractServiceImplTest.java
  otc-service/src/test/resources/features/e2e/buyingAndSellingOrders/buyingAndSellingOrdersFeatures.feature
  stock-service/src/test/java/rs/edu/raf/StockService/services/impl/FuturesContractImplTest.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/BankServiceCommunicationControllerTests.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/BankStockFacadeImplTests.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/ForexControllerTests.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/ForexServiceTests.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/FuturesContractImplTest.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/StockControllerTests.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/StockServiceTests.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/mapper/CurrencyInflationMapperTest.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/mapper/CurrencyMapperTest.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/mapper/ExchangeMapperTest.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/mapper/ForexMapperTest.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/mapper/FuturesContractMapperTest.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/mapper/OptionMapperTest.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/mapper/SecuritiesMapperTest.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/mapper/StockMapperTest.java
Labels: lgtm, approved, size/XXL

#392 Marzni racuni - final
  bank-service/src/main/java/rs/edu/raf/BankService/controller/MarginsTransactionController.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsAccountRequestDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsTransactionResponseDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/MarginsAccountMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/MarginsTransactionMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/MarginsTransactionService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsAccountServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsTransactionServiceImpl.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/MarginsAccountServiceImplTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/MarginsTransactionServiceImplTests.java
  stock-service/src/main/java/rs/edu/raf/StockService/services/facade/BankStockFacadeImpl.java
Labels: lgtm, approved, size/M

#393 marzne transakcije ispravljen e
  bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapTestData.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/MarginsTransactionController.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/BankStockDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsTransactionServiceImpl.java
  stock-service/src/main/java/rs/edu/raf/StockService/data/dto/BankStockDto.java
  stock-service/src/main/java/rs/edu/raf/StockService/services/facade/BankStockFacadeImpl.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/BankServiceCommunicationControllerTests.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/BankStockFacadeImplTests.java
Labels: lgtm, approved, size/M

#394 opet ispravljene marzne
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsTransactionServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
Labels: size/S, lgtm, approved

#396 deleted integration tests
  iam-service/src/test/java/rs/edu/raf/IAMService/integration/users/UserServiceIntegrationTests.java
  iam-service/src/test/java/rs/edu/raf/IAMService/integration/users/UserServiceIntegrationTestsConfig.java
  iam-service/src/test/java/rs/edu/raf/IAMService/integration/users/UserServiceTestsSteps.java
  iam-service/src/test/resources/features/integration/users/Activate Employee.feature
  iam-service/src/test/resources/features/integration/users/Get All Users.feature
  iam-service/src/test/resources/features/integration/users/Reset Agent Limit.feature
  iam-service/src/test/resources/features/integration/users/Update User.feature
Labels: size/L, lgtm, approved
