Repository RAF-SI-2023/Banka-2-Backend, pull requests merged in 2024-04, with the labels that each got.

#165 Update CurrencyRepository.java
  StockService/src/main/java/rs/edu/raf/StockService/repositories/CurrencyRepository.java
Labels: size/XS

#163 Krediti u bank servisu
  BankService/src/main/java/rs/edu/raf/BankService/BankServiceApplication.java
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
  BankService/src/main/java/rs/edu/raf/BankService/configuration/SpringSecurityConfig.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/CreditController.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/CreditDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/CreditRequestDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/Credit.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/CreditRequest.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/CreditRequestStatus.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/CreditType.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/CreditMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/credit/CreditRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/credit/CreditRequestRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/service/CreditService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
  IAMService/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapData.java
Labels: size/XL

#168 Issue #150 - Dovlacenje podatakka sa API-ja
  StockService/src/main/java/rs/edu/raf/StockService/bootstrap/BootstrapData.java
  StockService/src/main/java/rs/edu/raf/StockService/bootstrap/readers/ListingLoaders.java
  StockService/src/main/resources/application.properties
Labels: size/L

#167 API Option ruting
  StockService/pom.xml
  StockService/src/main/java/rs/edu/raf/StockService/bootstrap/BootstrapData.java
  StockService/src/main/java/rs/edu/raf/StockService/controllers/OptionController.java
  StockService/src/main/java/rs/edu/raf/StockService/data/dto/OptionDto.java
  StockService/src/main/java/rs/edu/raf/StockService/data/entities/Option.java
  StockService/src/main/java/rs/edu/raf/StockService/mapper/OptionMapper.java
  StockService/src/main/java/rs/edu/raf/StockService/repositories/OptionRepository.java
  StockService/src/main/java/rs/edu/raf/StockService/services/OptionService.java
  StockService/src/main/java/rs/edu/raf/StockService/services/impl/OptionServiceImpl.java
  StockService/src/main/resources/application.properties
  StockService/src/test/java/rs/edu/raf/StockService/OptionControllerTests.java
  StockService/src/test/java/rs/edu/raf/StockService/cucumber/CucumberIntegrationTest.java
  StockService/src/test/java/rs/edu/raf/StockService/cucumber/IntegrationTest.java
  StockService/src/test/java/rs/edu/raf/StockService/cucumber/controller/OptionControllerSteps.java
  StockService/src/test/resources/features/OptionController.feature
Labels: size/L

#164 Issue #112: BE - StockService - futures contrants
  StockService/src/main/java/rs/edu/raf/StockService/data/dto/FuturesContractDto.java
  StockService/src/main/java/rs/edu/raf/StockService/data/entities/FuturesContract.java
  StockService/src/main/java/rs/edu/raf/StockService/data/enums/FuturesContractType.java
  StockService/src/main/java/rs/edu/raf/StockService/mapper/FuturesContractMapper.java
  StockService/src/main/resources/csvs/future_data.csv
  StockService/src/test/java/rs/edu/raf/StockService/mapper/FuturesContractMapperTest.java
Labels: size/L

#169 Ispravljeni testovi za permisije
  IAMService/src/main/java/rs/edu/raf/IAMService/controllers/PermissionController.java
  IAMService/src/test/java/rs/edu/raf/IAMService/controllers/PermissionControllerTest.java
  IAMService/src/test/java/rs/edu/raf/IAMService/mapper/PermissionMapperTest.java
  IAMService/src/test/java/rs/edu/raf/IAMService/permissions/PermissionControllerUnitTest.java
  IAMService/src/test/java/rs/edu/raf/IAMService/services/impl/PermissionServiceImplTest.java
Labels: size/L

#170 Obrisane nepotrebne klase i zakomentarisani neki testovi
  IAMService/src/main/java/rs/edu/raf/IAMService/controllers/UserController.java
  IAMService/src/main/java/rs/edu/raf/IAMService/services/PasswordChangeTokenService.java
  IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/PasswordChangeTokenServiceImpl.java
  IAMService/src/main/java/rs/edu/raf/IAMService/utils/ChangedPasswordTokenUtil.java
  IAMService/src/main/java/rs/edu/raf/IAMService/utils/SubmitLimiter.java
  IAMService/src/main/java/rs/edu/raf/IAMService/validator/PasswordValidator.java
  IAMService/src/test/java/rs/edu/raf/IAMService/ChangedPasswordTokenUtilTest.java
  IAMService/src/test/java/rs/edu/raf/IAMService/PasswordChangeTest.java
  IAMService/src/test/java/rs/edu/raf/IAMService/PasswordResetTest.java
  IAMService/src/test/java/rs/edu/raf/IAMService/PasswordValidatorTest.java
  IAMService/src/test/java/rs/edu/raf/IAMService/SubmitLimiterTest.java
  IAMService/src/test/java/rs/edu/raf/IAMService/controllers/UserControllerTest.java
  NotificationService/src/test/java/rs/edu/raf/NotificationService/listenertest/RabbitMQListenersUnitTest.java
  StockService/src/test/java/rs/edu/raf/StockService/StockServiceApplicationTests.java
  StockService/src/test/java/rs/edu/raf/StockService/cucumber/CucumberIntegrationTest.java
  StockService/src/test/java/rs/edu/raf/StockService/cucumber/IntegrationTest.java
  StockService/src/test/resources/features/OptionController.feature
Labels: size/XL

#171 Testovi za metode kreiranja agenta u UserControllerTest i UserService…
  IAMService/src/test/java/rs/edu/raf/IAMService/UserServiceCrudTests.java
  IAMService/src/test/java/rs/edu/raf/IAMService/controllers/UserControllerTest.java
Labels: size/M

#186 unit+integracioni + findAccountsByEmail
  BankService/pom.xml
  BankService/src/main/java/rs/edu/raf/BankService/controller/AccountController.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/CreditController.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/AccountRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/service/AccountService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/AccountServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
  BankService/src/test/java/resources/creditFeatures.feature
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/CreditControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/CreditMapperTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/CreditServiceTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/integrationTests/CreditIntegrationTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/integrationTests/CreditStepsDefinition.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/integrationTests/CucumberSpringConfig.java
  OTCService/src/main/java/rs/edu/raf/OTCService/configuration/RabbitMQConfig.java
Labels: size/XL

#161 #151 Podrzano placanje uz verifikaciju
  BankService/src/main/java/rs/edu/raf/BankService/configuration/RabbitMQConfig.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/AccountController.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/TransactionController.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/ExternalTransferTransactionDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/GenericTransactionDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/InternalTransferTransactionDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/SavedAccountDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/TransactionVerificationDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/Account.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/ExternalTransferTransaction.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/InternalTransferTransaction.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/SavedAccount.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/Transaction.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/TransactionStatus.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/TransactionType.java
  BankService/src/main/java/rs/edu/raf/BankService/exception/InvalidInternalTransferException.java
  BankService/src/main/java/rs/edu/raf/BankService/exception/TransactionNotFoundException.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/TransactionMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/TransactionRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/service/AccountService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/TransactionService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/AccountServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  BankService/src/main/resources/application.properties
  IAMService/src/main/java/rs/edu/raf/IAMService/data/entites/User.java
  IAMService/src/main/java/rs/edu/raf/IAMService/repositories/UserRepository.java
Labels: size/XL

#189 msg
  .gitignore
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/OrderController.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/TransferTransactionController.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/OrderDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/TransferTransactionVerificationDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/Order.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/OrderActionType.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/OrderStatus.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/OrderType.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/AccountMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/CreditMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/OrderMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/TransactionMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/AccountRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/ForeignCurrencyHolderRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/OrderRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/TransactionRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/credit/CreditRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/credit/CreditRequestRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/service/AccountService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/CreditService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/OrderService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/AccountServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/CreditMapperTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/CreditServiceTests.java
  IAMService/src/main/java/rs/edu/raf/IAMService/data/entites/Agent.java
  IAMService/src/test/java/rs/edu/raf/IAMService/unit/UserServiceCrudTests.java
  IAMService/src/test/java/rs/edu/raf/IAMService/unit/controllers/UserControllerTest.java
  StockService/src/main/java/rs/edu/raf/StockService/bootstrap/readers/ListingLoaders.java
Labels: size/L, needs-rebase

#188 Unit testovi za RabbitMQListener i pristup resetovanju limita
  .gitignore
  IAMService/src/main/java/rs/edu/raf/IAMService/controllers/UserController.java
  NotificationService/src/test/java/rs/edu/raf/NotificationService/unit/listenertest/RabbitMQListenersSpringTest.java
  NotificationService/src/test/java/rs/edu/raf/NotificationService/unit/listenertest/RabbitMQListenersUnitTest.java
Labels: size/L

#190 jA SAM RETARDIRAN
  StockService/src/main/java/rs/edu/raf/StockService/services/impl/OptionServiceImpl.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/CucumberConfigurationTest.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/CucumberIntegrationTest.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/IntegrationTest.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/controller/OptionControllerSteps.java
  StockService/src/test/resources/application.properties
  StockService/src/test/resources/features/OptionController.feature
Labels: size/L

#192 Kartice i Novi korisnici u bootstrapu
  BankService/src/main/java/rs/edu/raf/BankService/controller/CardController.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/CardDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/card/Card.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/CardType.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/CardMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/CardRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/service/CardService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CardServiceImpl.java
  BankService/src/test/java/resources/cardFeatures.feature
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/CardControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/CardServiceTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/integrationTests/CardIntegrationSteps.java
  IAMService/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapData.java
Labels: size/XXL

#193 Issues<172> ucitavanje iz fajla i omoguceno dohvatanje svih futures c…
  StockService/src/main/java/rs/edu/raf/StockService/bootstrap/BootstrapData.java
  StockService/src/main/java/rs/edu/raf/StockService/bootstrap/readers/FuturesContractCsvReader.java
  StockService/src/main/java/rs/edu/raf/StockService/controllers/FuturesContractController.java
  StockService/src/main/java/rs/edu/raf/StockService/repositories/FuturesContractRepository.java
  StockService/src/main/java/rs/edu/raf/StockService/services/FuturesContractService.java
  StockService/src/main/java/rs/edu/raf/StockService/services/impl/FuturesContractImpl.java
  StockService/src/test/java/rs/edu/raf/StockService/services/impl/FuturesContractImplTest.java
Labels: size/L

#195 Dodata kartica i companija u BootstrapData
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
  IAMService/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapData.java
Labels: size/M

#194 Integracioni i end2end za hartije of vrednosti
  StockService/src/main/java/rs/edu/raf/StockService/controllers/ForexController.java
  StockService/src/main/java/rs/edu/raf/StockService/controllers/StockController.java
  StockService/src/main/java/rs/edu/raf/StockService/repositories/ForexRepository.java
  StockService/src/main/java/rs/edu/raf/StockService/repositories/StockRepository.java
  StockService/src/main/java/rs/edu/raf/StockService/services/ForexService.java
  StockService/src/main/java/rs/edu/raf/StockService/services/StockService.java
  StockService/src/main/java/rs/edu/raf/StockService/services/impl/ForexServiceImpl.java
  StockService/src/main/java/rs/edu/raf/StockService/services/impl/StockServiceImpl.java
  StockService/src/test/java/rs/edu/raf/StockService/e2e/forexcontroller/ForexControllerTests.java
  StockService/src/test/java/rs/edu/raf/StockService/e2e/forexcontroller/ForexControllerTestsConfig.java
  StockService/src/test/java/rs/edu/raf/StockService/e2e/forexcontroller/ForexControllerTestsSteps.java
  StockService/src/test/java/rs/edu/raf/StockService/e2e/stockcontroller/StockControllerTests.java
  StockService/src/test/java/rs/edu/raf/StockService/e2e/stockcontroller/StockControllerTestsConfig.java
  StockService/src/test/java/rs/edu/raf/StockService/e2e/stockcontroller/StockControllerTestsSteps.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/forexservice/ForexServiceImplTests.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/forexservice/ForexServiceImplTestsConfig.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/forexservice/ForexServiceImplTestsSteps.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/stockservice/StockServiceImplTests.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/stockservice/StockServiceImplTestsConfig.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/stockservice/StockServiceImplTestsSteps.java
  StockService/src/test/java/rs/edu/raf/StockService/unit/ForexControllerTests.java
  StockService/src/test/java/rs/edu/raf/StockService/unit/ForexServiceTests.java
  StockService/src/test/java/rs/edu/raf/StockService/unit/StockControllerTests.java
  StockService/src/test/java/rs/edu/raf/StockService/unit/StockServiceTests.java
  StockService/src/test/resources/features/e2e/forexcontroller/ForexController.feature
  StockService/src/test/resources/features/e2e/stockcontroller/StockController.feature
  StockService/src/test/resources/features/integration/forexservice/ForexServiceImpl.feature
  StockService/src/test/resources/features/integration/stockservice/StockServiceImpl.feature
Labels: size/XL

#199 CreditRequestovi updateovani da se vracaju samo pending
  BankService/src/main/java/rs/edu/raf/BankService/controller/CreditController.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/CreditRequestDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/credit/Credit.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/credit/CreditRequest.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/credit/CreditRequestRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
Labels: size/S

#202 Menjacnica+Credit Testovi
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/exchangeRatesUtils/ExchangeRateApiResponse.java
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/exchangeRatesUtils/ExchangeRateBootstrapUtil.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/CurrencyExchangeController.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/ExchangeRatesDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/ExchangeRequestDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/ExchangeTransferDetailsDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/exchangeCurrency/ExchangeRates.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/exchangeCurrency/ExchangeTransferTransactionDetails.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/AccountType.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/TransactionType.java
  BankService/src/main/java/rs/edu/raf/BankService/exception/NotEnoughFundsException.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/ExchangeRatesMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/ExchangeTransferDetailsMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/TransactionMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/ExchangeRateRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/service/AccountService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/CurrencyExchangeService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/AccountServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CurrencyExchangeServiceImpl.java
  BankService/src/test/java/resources/integration/cardFeatures.feature
  BankService/src/test/java/resources/integration/creditFeatures.feature
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/e2e/CreditControllerConfigTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/e2e/CreditControllerStateTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/e2e/CreditControllerTestSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/e2e/CreditControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/e2e/generators/JwtTokenGenerator.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/integrationTests/CreditIntegrationTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/unit/CardControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/unit/CardServiceTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/unit/CreditControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/unit/CreditMapperTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/unit/CreditServiceTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/unit/ExchangeControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/unit/ExchangeRatesMapperTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/unit/ExchangeServiceTests.java
  BankService/src/test/resources/features/e2e/creditController/creditFeaturesE2E.feature
  BankService/src/test/resources/features/integration/card-integration/cardFeatures.feature
  BankService/src/test/resources/features/integration/credit-integration/creditFeatures.feature
  IAMService/src/main/java/rs/edu/raf/IAMService/controllers/CompanyController.java
Labels: size/XXL

#203 added support for transaction-verification proces
  BankService/src/main/java/rs/edu/raf/BankService/configuration/RabbitMQConfig.java
  BankService/src/test/java/resources/integration/creditFeatures.feature
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/integrationTests/CucumberSpringConfig.java
  BankService/src/test/resources/features/integration/credit-integration/cardFeatures.feature
  NotificationService/src/main/java/rs/edu/raf/NotificationService/configuration/RabbitMQConfig.java
  NotificationService/src/main/java/rs/edu/raf/NotificationService/data/dto/TransferTransactionVerificationDto.java
  NotificationService/src/main/java/rs/edu/raf/NotificationService/listener/RabbitMQListeners.java
  NotificationService/src/main/java/rs/edu/raf/NotificationService/mapper/EmailDtoMapper.java
Labels: size/M

#205 #173 Odradjeni integracioni testovi za placanja
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/CreateExternalTransactionIntegrationTest.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/CreateInternalTransactionIntegrationTest.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/GetTransferTransactionIntegrationTest.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/TransactionServiceIntegrationTest.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/TransactionServiceIntegrationTestConfig.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/VerifyTransactionIntegrationTest.java
  BankService/src/test/resources/transaction-integration/fetch_transactions.feature
  BankService/src/test/resources/transaction-integration/make_external_transaction.feature
  BankService/src/test/resources/transaction-integration/make_internal_transaction.feature
  BankService/src/test/resources/transaction-integration/verify_transaction.feature
Labels: size/XL

#206 prmenio token za exchangerate. promnio strukturu testova
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/exchangeRatesUtils/ExchangeRateBootstrapUtil.java
  BankService/src/test/java/rs/edu/raf/BankService/BankServiceApplicationTests.java
  BankService/src/test/java/rs/edu/raf/BankService/creditTests/integrationTests/credit/CucumberSpringConfig.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/credit/CreditControllerConfigTests.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/credit/CreditControllerStateTests.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/credit/CreditControllerTestSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/credit/CreditControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/credit/generators/JwtTokenGenerator.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/card/CardServiceImplSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/card/CardServiceImplTests.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/card/CardServiceImplTestsConfig.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/credit/CreditIntegrationTests.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/credit/CreditStepsDefinition.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/credit/CucumberSpringConfig.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/cardTests/CardControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/cardTests/CardServiceTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/creditTests/CreditControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/creditTests/CreditMapperTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/creditTests/CreditServiceTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeRatesMapperTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeServiceTests.java
  BankService/src/test/resources/features/integration/credit-integration/cardFeatures.feature
Labels: size/M

#207 Izmene
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/CardDto.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/CardMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/service/CardService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CardServiceImpl.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/card/CardControllerJwtConst.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/card/CardControllerSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/card/CardControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/card/CardControllerTestsConfig.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/credit/CreditControllerTestSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/generators/JwtTokenGenerator.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/card/CardServiceImplSteps.java
  BankService/src/test/resources/features/e2e/cardController/cardFeaturesController.feature
  BankService/src/test/resources/features/integration/card-integration/cardFeatures.feature
Labels: size/L

#196 Aleksa subaranovic raf/issue176 integracioni,e2e,emailSenderTestFix
  IAMService/src/main/java/rs/edu/raf/IAMService/data/entites/User.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/s.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerE2ETests.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerE2ETestsConfig.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerTestsState.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerTestsSteps.java
  IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/UserServiceIntegrationTests.java
  IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/UserServiceIntegrationTestsConfig.java
  IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/UserServiceTestsSteps.java
  IAMService/src/test/resources/features/e2e/usercontroller/deleteUserByEmail.feature
  IAMService/src/test/resources/features/e2e/usercontroller/getAllUsers.feature
  IAMService/src/test/resources/features/e2e/usercontroller/resetAgentLimit.feature
  IAMService/src/test/resources/features/e2e/usercontroller/updateUsers.feature
  IAMService/src/test/resources/features/integration/userservice/Activate Employee.feature
  IAMService/src/test/resources/features/integration/userservice/Get All Users.feature
  IAMService/src/test/resources/features/integration/userservice/Reset Agent Limit.feature
  IAMService/src/test/resources/features/integration/userservice/Update User.feature
  IAMService/src/test/resources/junit-platform.properties
  NotificationService/src/main/resources/application.properties
  NotificationService/src/test/java/rs/edu/raf/NotificationService/unit/EmailServiceTests.java
Labels: size/XL

#209 Issue #178 - Integracioni testovi za Exchange
  StockService/src/test/java/rs/edu/raf/StockService/integration/exchangeservice/ExchangeServiceImplTests.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/exchangeservice/ExchangeServiceImplTestsConfig.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/exchangeservice/ExchangeServiceImplTestsSteps.java
  StockService/src/test/resources/features/integration/exchangeservice/ExchangeServiceImpl.feature
Labels: size/L

#212 Finished e2e Exchange tests
  StockService/src/main/java/rs/edu/raf/StockService/controllers/ExchangeController.java
  StockService/src/main/java/rs/edu/raf/StockService/services/impl/ExchangeServiceImpl.java
  StockService/src/main/java/rs/edu/raf/StockService/services/impl/InMemoryExchangeServiceImpl.java
  StockService/src/test/java/rs/edu/raf/StockService/e2e/exchangecontroller/ExchangeControllerTests.java
  StockService/src/test/java/rs/edu/raf/StockService/e2e/exchangecontroller/ExchangeControllerTestsConfig.java
  StockService/src/test/java/rs/edu/raf/StockService/e2e/exchangecontroller/ExchangeControllerTestsSteps.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/exchangeservice/ExchangeServiceImplTestsSteps.java
  StockService/src/test/resources/features/e2e/exchangecontroller/ExchangeController.feature
  StockService/src/test/resources/features/integration/exchangeservice/ExchangeServiceImpl.feature
Labels: size/L

#213 futures contract @CrossOrigin + findById
  StockService/src/main/java/rs/edu/raf/StockService/controllers/FuturesContractController.java
  StockService/src/main/java/rs/edu/raf/StockService/services/FuturesContractService.java
  StockService/src/main/java/rs/edu/raf/StockService/services/impl/FuturesContractImpl.java
Labels: size/S

#214 Uradjeni e2e testovi za CurrencyExchangeController/Menjacnicu
  BankService/src/test/java/rs/edu/raf/BankService/e2e/currencyExchange/CurrencyExchangeControllerConfigTests.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/currencyExchange/CurrencyExchangeControllerStateTests.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/currencyExchange/CurrencyExchangeControllerTestSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/currencyExchange/CurrencyExchangeControllerTests.java
  BankService/src/test/resources/features/e2e/currencyExchangeController/currencyExchangeFeatuesE2E.feature
Labels: size/L

#215 #173 Odradjeni e2e testovi za placanja i izmenjen jedan integracioni
  BankService/src/test/java/rs/edu/raf/BankService/e2e/transaction/TransferTransactionE2ETests.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/CreateInternalTransactionIntegrationTest.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/TransactionServiceIntegrationTest.java
  BankService/src/test/resources/features/integration/transaction-integration/fetch_transactions.feature
  BankService/src/test/resources/features/integration/transaction-integration/make_external_transaction.feature
  BankService/src/test/resources/features/integration/transaction-integration/make_internal_transaction.feature
  BankService/src/test/resources/features/integration/transaction-integration/verify_transaction.feature
Labels: size/L

#221 obrisan cors in user kontrolera
  IAMService/src/main/java/rs/edu/raf/IAMService/controllers/UserController.java
Labels: size/XS

#223 Fix za kredite
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/AccountServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/credit/CreditControllerTestSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/credit/CreditStepsDefinition.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/creditTests/CreditServiceTests.java
Labels: size/L

#224 merge from dev to main
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/AccountServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/credit/CreditControllerTestSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/credit/CreditStepsDefinition.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/creditTests/CreditServiceTests.java
Labels: size/L

#225 vise se ne koristi foreignAccHolder
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/exchangeRatesUtils/ExchangeRateBootstrapUtil.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/ExchangeRequestDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/accounts/ForeignCurrencyAccount.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CurrencyExchangeServiceImpl.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/currencyExchange/CurrencyExchangeControllerTestSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/creditTests/CreditServiceTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeServiceTests.java
  BankService/src/test/resources/features/e2e/currencyExchangeController/currencyExchangeFeatuesE2E.feature
Labels: size/L

#227 bugifix
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
Labels: size/XS

#228 zandreja
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/CurrencyExchangeController.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/currencyExchange/CurrencyExchangeControllerTestSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeControllerTests.java
Labels: size/S

#220 testovi fixes
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/usercontroller/UserControllerStateTests.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/usercontroller/UserControllerTest.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/usercontroller/UserControllerTestConfig.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/usercontroller/UserControllerTestSteps.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerE2ETests.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerE2ETestsConfig.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerE2ETestsState.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerE2ETestsSteps.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerTestsState.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerTestsSteps.java
  IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/UserServiceIntegrationTests.java
  IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/UserServiceIntegrationTestsConfig.java
  IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/UserServiceTestsSteps.java
  IAMService/src/test/resources/features/e2e/usercontroller/deleteUserByEmail.feature
  IAMService/src/test/resources/features/e2e/usercontroller/getAllUsers.feature
  IAMService/src/test/resources/features/e2e/usercontroller/resetAgentLimit.feature
  IAMService/src/test/resources/features/e2e/usercontroller/updateUsers.feature
  IAMService/src/test/resources/features/e2e/users/deleteUserByEmail.feature
  IAMService/src/test/resources/features/e2e/users/getAllUsers.feature
  IAMService/src/test/resources/features/e2e/users/resetAgentLimit.feature
  IAMService/src/test/resources/features/e2e/users/updateUsers.feature
  IAMService/src/test/resources/features/integration/users/Activate Employee.feature
  IAMService/src/test/resources/features/integration/users/Get All Users.feature
  IAMService/src/test/resources/features/integration/users/Reset Agent Limit.feature
  IAMService/src/test/resources/features/integration/users/Update User.feature
  IAMService/src/test/resources/features/integration/userservice/Activate Employee.feature
  IAMService/src/test/resources/features/integration/userservice/Get All Users.feature
  IAMService/src/test/resources/features/integration/userservice/Reset Agent Limit.feature
  IAMService/src/test/resources/features/integration/userservice/Update User.feature
Labels: size/XXL

#229 novi token za exchangerate api
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/exchangeRatesUtils/ExchangeRateBootstrapUtil.java
Labels: size/XS

#230 merge dev to main
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/exchangeRatesUtils/ExchangeRateBootstrapUtil.java
  BankService/src/main/java/rs/edu/raf/BankService/controller/CurrencyExchangeController.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/ExchangeRequestDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/accounts/ForeignCurrencyAccount.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CurrencyExchangeServiceImpl.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/currencyExchange/CurrencyExchangeControllerTestSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/creditTests/CreditServiceTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeServiceTests.java
  BankService/src/test/resources/features/e2e/currencyExchangeController/currencyExchangeFeatuesE2E.feature
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/usercontroller/UserControllerStateTests.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/usercontroller/UserControllerTest.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/usercontroller/UserControllerTestConfig.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/usercontroller/UserControllerTestSteps.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerE2ETests.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerE2ETestsConfig.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerE2ETestsState.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerE2ETestsSteps.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerTestsState.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerTestsSteps.java
  IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/UserServiceIntegrationTests.java
  IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/UserServiceIntegrationTestsConfig.java
  IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/UserServiceTestsSteps.java
  IAMService/src/test/resources/features/e2e/usercontroller/deleteUserByEmail.feature
  IAMService/src/test/resources/features/e2e/usercontroller/getAllUsers.feature
  IAMService/src/test/resources/features/e2e/usercontroller/resetAgentLimit.feature
  IAMService/src/test/resources/features/e2e/usercontroller/updateUsers.feature
  IAMService/src/test/resources/features/e2e/users/deleteUserByEmail.feature
  IAMService/src/test/resources/features/e2e/users/getAllUsers.feature
  IAMService/src/test/resources/features/e2e/users/resetAgentLimit.feature
  IAMService/src/test/resources/features/e2e/users/updateUsers.feature
  IAMService/src/test/resources/features/integration/users/Activate Employee.feature
  IAMService/src/test/resources/features/integration/users/Get All Users.feature
  IAMService/src/test/resources/features/integration/users/Reset Agent Limit.feature
  IAMService/src/test/resources/features/integration/users/Update User.feature
  IAMService/src/test/resources/features/integration/userservice/Activate Employee.feature
  IAMService/src/test/resources/features/integration/userservice/Get All Users.feature
  IAMService/src/test/resources/features/integration/userservice/Reset Agent Limit.feature
  IAMService/src/test/resources/features/integration/userservice/Update User.feature
Labels: size/XXL

#219 Integracioni testovi za kompanije i currency
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/companycontroller/CompanyControllerSteps.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/companycontroller/CompanyControllerTests.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/companycontroller/CompanyControllerTestsConfig.java
  IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/company/CompanyServiceTests.java
  IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/company/CompanyServiceTestsConfig.java
  IAMService/src/test/java/rs/edu/raf/IAMService/integration/users/company/CompanyServiceTestsSteps.java
  IAMService/src/test/resources/features/companyservice/Create Company.feature
  IAMService/src/test/resources/features/companyservice/Delete Company By Identification Num.feature
  IAMService/src/test/resources/features/companyservice/Get Companies.feature
  IAMService/src/test/resources/features/companyservice/Update Company.feature
  IAMService/src/test/resources/features/e2e/companycontroller/CompanyController.feature
  StockService/src/test/java/rs/edu/raf/StockService/e2e/currencycontroller/CurrencyControllerTests.java
  StockService/src/test/java/rs/edu/raf/StockService/e2e/currencycontroller/CurrencyControllerTestsConfig.java
  StockService/src/test/java/rs/edu/raf/StockService/e2e/currencycontroller/CurrencyControllerTestsSteps.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/currencyservice/CurrencyServiceImplTests.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/currencyservice/CurrencyServiceImplTestsConfig.java
  StockService/src/test/java/rs/edu/raf/StockService/integration/currencyservice/CurrencyServiceImplTestsSteps.java
  StockService/src/test/resources/features/e2e/currencycontroller/CurrencyController.feature
  StockService/src/test/resources/features/integration/currencyservice/CurrencyServiceImpl.feature
Labels: size/XL

#236 bootstrap data za andreja da bude smislenije, i credit req buffxi
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/AccountServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
  IAMService/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapData.java
Labels: size/L

#237 Testovi+otc user
  IAMService/src/main/java/rs/edu/raf/IAMService/controllers/UserController.java
  IAMService/src/main/java/rs/edu/raf/IAMService/data/dto/CompanyEmployeeDto.java
  IAMService/src/main/java/rs/edu/raf/IAMService/data/entites/CompanyEmployee.java
  IAMService/src/main/java/rs/edu/raf/IAMService/mapper/UserMapper.java
  IAMService/src/main/java/rs/edu/raf/IAMService/services/UserService.java
  IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/UserServiceImpl.java
  IAMService/src/test/java/rs/edu/raf/IAMService/unit/UserServiceCrudTests.java
  IAMService/src/test/java/rs/edu/raf/IAMService/unit/controllers/RoleControllerUnitTest.java
  IAMService/src/test/java/rs/edu/raf/IAMService/unit/controllers/UserControllerTest.java
  IAMService/src/test/java/rs/edu/raf/IAMService/unit/services/RoleServiceImplUnitTest.java
  IAMService/src/test/java/rs/edu/raf/IAMService/unit/services/UserServiceImplTest.java
  StockService/src/main/java/rs/edu/raf/StockService/controllers/CurrencyController.java
  StockService/src/main/java/rs/edu/raf/StockService/services/impl/InMemoryCurrencyServiceImpl.java
  StockService/src/test/java/rs/edu/raf/StockService/unit/CurrencyControllerTests.java
  StockService/src/test/java/rs/edu/raf/StockService/unit/CurrencyServiceTests.java
  StockService/src/test/java/rs/edu/raf/StockService/unit/ExchangeControllerTests.java
  StockService/src/test/java/rs/edu/raf/StockService/unit/ForexControllerTests.java
  StockService/src/test/java/rs/edu/raf/StockService/unit/FutureServiceImplTests.java
  StockService/src/test/java/rs/edu/raf/StockService/unit/FuturesContractControllerTests.java
  StockService/src/test/java/rs/edu/raf/StockService/unit/OptionControllerTests.java
  StockService/src/test/java/rs/edu/raf/StockService/unit/OptionServiceImplTests.java
  StockService/src/test/java/rs/edu/raf/StockService/unit/StockControllerTests.java
Labels: size/XL

#238 male izmene
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/OrderDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/Order.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/accounts/BusinessCashAccount.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/accounts/CashAccount.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/accounts/DomesticCurrencyCashAccount.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/accounts/ForeignCurrencyCashAccount.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/accounts/ForeignCurrencyHolder.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/transactions/TransferTransaction.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/SecuritiesType.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/AccountMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/ExchangeTransferDetailsMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/OrderMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/TransactionMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/AccountRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/AccountServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CardServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CurrencyExchangeServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/currencyExchange/CurrencyExchangeControllerTestSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/transaction/TransferTransactionE2ETests.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/CreateExternalTransactionIntegrationTest.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/CreateInternalTransactionIntegrationTest.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/GetTransferTransactionIntegrationTest.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/VerifyTransactionIntegrationTest.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/cardTests/CardServiceTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/creditTests/CreditServiceTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeRatesMapperTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeServiceTests.java
  NotificationService/src/main/java/rs/edu/raf/NotificationService/mapper/EmailDtoMapper.java
Labels: size/XL

#239 izmene
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
  BankService/src/main/java/rs/edu/raf/BankService/data/dto/OrderDto.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/Order.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/accounts/BusinessCashAccount.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/accounts/CashAccount.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/accounts/DomesticCurrencyCashAccount.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/accounts/ForeignCurrencyCashAccount.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/accounts/ForeignCurrencyHolder.java
  BankService/src/main/java/rs/edu/raf/BankService/data/entities/transactions/TransferTransaction.java
  BankService/src/main/java/rs/edu/raf/BankService/data/enums/SecuritiesType.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/AccountMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/ExchangeTransferDetailsMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/OrderMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/mapper/TransactionMapper.java
  BankService/src/main/java/rs/edu/raf/BankService/repository/AccountRepository.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/AccountServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CardServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CreditServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/CurrencyExchangeServiceImpl.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/currencyExchange/CurrencyExchangeControllerTestSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/transaction/TransferTransactionE2ETests.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/CreateExternalTransactionIntegrationTest.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/CreateInternalTransactionIntegrationTest.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/GetTransferTransactionIntegrationTest.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/transactionservice/VerifyTransactionIntegrationTest.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/cardTests/CardServiceTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/creditTests/CreditServiceTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeRatesMapperTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/exchangeTests/ExchangeServiceTests.java
  NotificationService/src/main/java/rs/edu/raf/NotificationService/mapper/EmailDtoMapper.java
Labels: size/XL

#242 Uradjeni unit testovi za OptionServiceImpl
  StockService/src/main/java/rs/edu/raf/StockService/services/OptionService.java
  StockService/src/main/java/rs/edu/raf/StockService/services/impl/OptionServiceImpl.java
  StockService/src/test/java/rs/edu/raf/StockService/unit/OptionServiceImplTests.java
Labels: size/L

#244 da se ucitava iz fajla bootstrap
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapData.java
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/exchangeRatesUtils/ExchangeRateApiResponse.java
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/exchangeRatesUtils/ExchangeRateBootstrapUtil.java
  BankService/src/main/resources/exchangeRatesDev/exchangeRates.exc
  StockService/src/main/java/rs/edu/raf/StockService/bootstrap/readers/ListingLoaders.java
  StockService/src/main/java/rs/edu/raf/StockService/data/entities/Listing.java
  StockService/src/main/resources/application.properties
  StockService/src/main/resources/serializedData/forex.exc
  StockService/src/main/resources/serializedData/stock.exc
Labels: size/L

#245 Sredjivanje podataka za bazu i prilagodjavanje testova izmenama
  BankService/pom.xml
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapTestData.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/card/CardControllerSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/credit/CreditControllerTestSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/currencyExchange/CurrencyExchangeControllerTestSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/card/CardServiceImplSteps.java
  BankService/src/test/java/rs/edu/raf/BankService/integration/credit/CreditStepsDefinition.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/creditTests/CreditServiceTests.java
  BankService/src/test/resources/features/e2e/cardController/cardFeaturesController.feature
  BankService/src/test/resources/features/e2e/currencyExchangeController/currencyExchangeFeatuesE2E.feature
  BankService/src/test/resources/features/integration/card-integration/cardFeatures.feature
  BankService/src/test/resources/features/integration/credit-integration/creditFeatures.feature
  BankService/src/test/resources/features/integration/transaction-integration/fetch_transactions.feature
  BankService/src/test/resources/features/integration/transaction-integration/make_external_transaction.feature
  BankService/src/test/resources/features/integration/transaction-integration/make_internal_transaction.feature
  BankService/src/test/resources/features/integration/transaction-integration/verify_transaction.feature
  IAMService/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapTestData.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/usercontroller/UserControllerTestSteps.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/users/UserControllerE2ETestsSteps.java
  IAMService/src/test/resources/features/e2e/usercontroller/UserController.feature
  IAMService/src/test/resources/features/e2e/users/getAllUsers.feature
  IAMService/src/test/resources/features/e2e/users/resetAgentLimit.feature
  IAMService/src/test/resources/features/e2e/users/updateUsers.feature
  StockService/src/main/resources/serializedData/stock.exc
Labels: size/XL

#246 sredjivanje koda
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  BankService/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapTestData.java
  BankService/src/test/java/rs/edu/raf/BankService/e2e/currencyExchange/CurrencyExchangeControllerTestSteps.java
  IAMService/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapDevData.java
  IAMService/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapTestData.java
  IAMService/src/test/java/rs/edu/raf/IAMService/e2e/usercontroller/UserControllerTestSteps.java
  IAMService/src/test/java/rs/edu/raf/IAMService/unit/controllers/AuthControllerTest.java
  NotificationService/src/main/java/rs/edu/raf/NotificationService/listener/RabbitMQListeners.java
  NotificationService/src/test/java/rs/edu/raf/NotificationService/NotificationServiceApplicationTests.java
  StockService/src/main/java/rs/edu/raf/StockService/bootstrap/BootstrapData.java
  StockService/src/main/java/rs/edu/raf/StockService/bootstrap/exchange/BootstrapExchange.java
  StockService/src/main/java/rs/edu/raf/StockService/bootstrap/readers/ListingLoaders.java
  StockService/src/main/java/rs/edu/raf/StockService/services/impl/OptionServiceImpl.java
  StockService/src/main/resources/serializedData/stock.exc
Labels: size/L

#247 obrisao metode u servisu koje se ne koriste
  NotificationService/src/main/java/rs/edu/raf/NotificationService/services/EmailService.java
Labels: size/S

#250 unit testovi za account
  .prow/StockService.yaml
  BankService/src/main/java/rs/edu/raf/BankService/controller/OrderController.java
  BankService/src/main/java/rs/edu/raf/BankService/service/OrderService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/account/AccountControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/account/AccountServiceTests.java
  StockService/src/main/resources/application.properties
  docker-compose.yml
Labels: size/XL

#251 dodati unit testovi za accounts
  .prow/StockService.yaml
  BankService/src/main/java/rs/edu/raf/BankService/controller/OrderController.java
  BankService/src/main/java/rs/edu/raf/BankService/service/OrderService.java
  BankService/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/account/AccountControllerTests.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/account/AccountServiceTests.java
  StockService/src/main/resources/application.properties
  docker-compose.yml
Labels: size/XL

#252 andrej delete user
  IAMService/src/main/java/rs/edu/raf/IAMService/controllers/UserController.java
  IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/UserServiceImpl.java
Labels: size/XS

#253 andrej security za supervisora
  IAMService/src/main/java/rs/edu/raf/IAMService/controllers/UserController.java
  IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/UserServiceImpl.java
Labels: size/S

#254 bugfix za createuser
  IAMService/src/main/java/rs/edu/raf/IAMService/services/impl/UserServiceImpl.java
Labels: size/S

#256 Testovi za account controller
  BankService/pom.xml
  BankService/src/main/java/rs/edu/raf/BankService/controller/AccountController.java
  BankService/src/test/java/rs/edu/raf/BankService/unit/account/AccountControllerTests.java
  IAMService/pom.xml
  IAMService/src/test/java/rs/edu/raf/IAMService/unit/services/UserServiceImplTest.java
  NotificationService/pom.xml
  OTCService/pom.xml
  StockService/pom.xml
Labels: size/L

#261 Create OWNERS
  OWNERS
Labels: size/XS

#262 Create OWNERS
  OWNERS
Labels: size/XS
