Repository RAF-SI-2023/Banka-2-Backend, pull requests merged in 2024-06, with the labels that each got.

#330 Update build.yaml
  .prow/build.yaml
Labels: approved, size/XS

#331 merge
  .prow/build.yaml
Labels: lgtm, approved, size/XS

#332 Izmenjena Kartica
  bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/CardController.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/CardDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/entities/card/Card.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/CardMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/CardService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/CardServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/CurrencyExchangeServiceImpl.java
Labels: lgtm, approved, size/M

#333 Profit za individualne agente, samo za akcije i Profit na nivou celokupne banke
  bank-service/pom.xml
  bank-service/src/main/java/rs/edu/raf/BankService/controller/ActionAgentProfitController.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/BankProfitController.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/ActionAgentProfitDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/BankProfitDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/TotalActionAgentProfitDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/entities/profit/ActionAgentProfit.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/entities/profit/BankProfit.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/enums/TransactionProfitType.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/ActionAgentProfitMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/BankProfitMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/repository/ActionAgentProfitRepository.java
  bank-service/src/main/java/rs/edu/raf/BankService/repository/BankProfitRepository.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/ActionAgentProfitService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/BankProfitService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/ActionAgentProfitServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/BankProfitServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
Labels: size/L, lgtm, approved

#334 Dodat listing type u securitesOwnersip
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/SecuritiesOwnershipDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/entities/SecuritiesOwnership.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/SecuritiesOwnershipMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
Labels: size/S, lgtm, approved

#324 Aleksa subaranovic raf/issue322
  otc-service/src/main/java/rs/edu/raf/OTCService/controllers/ContractController.java
  otc-service/src/main/java/rs/edu/raf/OTCService/service/impl/ContractServiceImpl.java
  otc-service/src/main/resources/application-dev.properties
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/contracts/ContractsE2ETests.java
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/contracts/ContractsE2ETestsConfig.java
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/contracts/ContractsE2ETestsState.java
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/contracts/ContractsE2ETestsSteps.java
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/generators/JwtTokenGenerator.java
  otc-service/src/test/java/rs/edu/raf/OTCService/integration/contracts/ContractsServiceIntegrationTests.java
  otc-service/src/test/java/rs/edu/raf/OTCService/integration/contracts/ContractsServiceIntegrationTestsConfig.java
  otc-service/src/test/java/rs/edu/raf/OTCService/integration/contracts/ContractsServiceTestsSteps.java
  otc-service/src/test/java/rs/edu/raf/OTCService/unit/controllers/ContractControllerImplTest.java
  otc-service/src/test/java/rs/edu/raf/OTCService/unit/services/ContractServiceImplTest.java
  otc-service/src/test/resources/features/e2e/contracts/ApproveContracts.feature
  otc-service/src/test/resources/features/e2e/contracts/DenyContracts.feature
  otc-service/src/test/resources/features/integration/contracts/ContractsApproved.feature
  otc-service/src/test/resources/features/integration/contracts/CreateContracts.feature
  otc-service/src/test/resources/features/integration/contracts/GetContracts.feature
  otc-service/src/test/resources/junit-platform.properties
Labels: lgtm, approved, size/XXL

#336 Dodate rute o Order
  bank-service/src/main/java/rs/edu/raf/BankService/controller/ActionAgentProfitController.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/ActionAgentProfitService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/ActionAgentProfitServiceImpl.java
  otc-service/src/main/java/rs/edu/raf/OTCService/controllers/ContractController.java
  otc-service/src/main/java/rs/edu/raf/OTCService/repositories/ContractRepository.java
  otc-service/src/main/java/rs/edu/raf/OTCService/service/ContractService.java
  otc-service/src/main/java/rs/edu/raf/OTCService/service/impl/ContractServiceImpl.java
Labels: lgtm, approved, size/M

#338 #314
  bank-service/src/main/java/rs/edu/raf/BankService/controller/SecuritiesOwnershipsController.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/entities/SecuritiesOwnership.java
  bank-service/src/main/java/rs/edu/raf/BankService/repository/SecuritiesOwnershipRepository.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/SecuritiesOwnershipService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/SecuritiesOwnershipServiceImpl.java
  bank-service/src/test/java/rs/edu/raf/BankService/e2e/securityOwnership/SecurityOwnershipControllerSteps.java
  bank-service/src/test/java/rs/edu/raf/BankService/integration/securityOwnership/SecurityOwnershipsImplSteps.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/securitiesOwnerships/SecuritiesOwnershipsControllerTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/securitiesOwnerships/SecuritiesOwnershipsServiceTests.java
  bank-service/src/test/resources/features/e2e/securityOwnership/securityOwnershipFeatures.feature
  bank-service/src/test/resources/features/integration/securitiesOwnership-integration/securitiesOwnershipFeatures.feature
Labels: size/L, lgtm, approved

#340 security ownership ponovo radi
  bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/SecuritiesOwnershipMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/StockServiceImpl.java
  stock-service/src/main/java/rs/edu/raf/StockService/controllers/ExchangeController.java
  stock-service/src/test/java/rs/edu/raf/StockService/e2e/exchangecontroller/ExchangeControllerTestsSteps.java
Labels: size/S, lgtm, approved

#341 Skoro zavrsen marzni racun
  bank-service/src/main/java/rs/edu/raf/BankService/MarginsAccountMaintainScheduler.java
  bank-service/src/main/java/rs/edu/raf/BankService/configuration/RabbitMQConfig.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/MarginsAccountController.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/MarginsTransactionController.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginCallViolationDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsAccountRequestDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsAccountResponseDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsTransactionRequestDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsTransactionResponseDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/entities/MarginsAccount.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/entities/MarginsTransaction.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/MarginsAccountMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/MarginsTransactionMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/repository/MarginsTransactionRepository.java
  bank-service/src/main/java/rs/edu/raf/BankService/repository/specification/MarginsTransactionSpecification.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/MarginsAccountService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/MarginsTransactionService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsAccountServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsTransactionServiceImpl.java
  notification-service/src/main/java/rs/edu/raf/NotificationService/data/dto/MarginCallViolationDto.java
  notification-service/src/main/java/rs/edu/raf/NotificationService/listener/RabbitMQListeners.java
  stock-service/src/main/java/rs/edu/raf/StockService/configuration/SpringSecurityConfig.java
  stock-service/src/main/java/rs/edu/raf/StockService/controllers/BankServiceCommunicationController.java
Labels: size/XL, lgtm, approved

#343 Test coverage ignore
  bank-service/pom.xml
Labels: lgtm, approved, size/XS

#344 test coverage exclusion
  README.md
  bank-service/pom.xml
Labels: lgtm, approved, size/XS

#347 Editovan transferTransactionDetails
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/BankTransferTransactionDetailsServiceImpl.java
Labels: lgtm, approved, size/XS

#348 Revert "Editovan transferTransactionDetails"
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/BankTransferTransactionDetailsServiceImpl.java
Labels: lgtm, approved, size/XS

#351 Bugfix za currencyexchange test
  bank-service/src/main/java/rs/edu/raf/BankService/service/BankTransferTransactionDetailsService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/BankTransferTransactionDetailsServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/CurrencyExchangeServiceImpl.java
  bank-service/src/test/resources/features/e2e/currencyExchangeController/currencyExchangeFeatuesE2E.feature
Labels: lgtm, approved, size/M

#346 test coverage exlusion
  bank-service/pom.xml
Labels: lgtm, approved, size/XS

#350 #319 i #320
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  bank-service/src/test/java/rs/edu/raf/BankService/e2e/orderTransaction/OrderTransactionControllerConfigTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/e2e/orderTransaction/OrderTransactionControllerStateTest.java
  bank-service/src/test/java/rs/edu/raf/BankService/e2e/orderTransaction/OrderTransactionControllerTestSteps.java
  bank-service/src/test/java/rs/edu/raf/BankService/e2e/orderTransaction/OrderTransactionControllerTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/integration/orderTransaction/FindAllOrderTransactionsByAccountNumberIntegrationTest.java
  bank-service/src/test/java/rs/edu/raf/BankService/integration/orderTransaction/FindAllOrderTransactionsIntegrationTest.java
  bank-service/src/test/java/rs/edu/raf/BankService/integration/orderTransaction/FindOrderTransactionByIdIntegrationTest.java
  bank-service/src/test/java/rs/edu/raf/BankService/integration/orderTransaction/FindOrderTransactionByOrderIdIntegrationTest.java
  bank-service/src/test/java/rs/edu/raf/BankService/integration/orderTransaction/OrderTransactionIntegrationTest.java
  bank-service/src/test/java/rs/edu/raf/BankService/integration/orderTransaction/OrderTransactionIntegrationTestConfig.java
  bank-service/src/test/java/rs/edu/raf/BankService/integration/transactionservice/DepositWithdrawalTransactionIntegrationTest.java
  bank-service/src/test/java/rs/edu/raf/BankService/integration/transactionservice/TransferFundsIntegrationTest.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/orderTransaction/OrderTransactionControllerTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/orderTransaction/OrderTransactionServiceTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/transferTransaction/TransferControllerTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/transferTransaction/TransferService.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/transferTransaction/TransferServiceTests.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/transferTransaction/TrasnferController.java
  bank-service/src/test/resources/features/e2e/orderTransactionController/orderTransactionControllerFeatures.feature
  bank-service/src/test/resources/features/integration/orderTransaction-integration/find_all_order_transactions.feature
  bank-service/src/test/resources/features/integration/orderTransaction-integration/find_order_transaction_by_id.feature
  bank-service/src/test/resources/features/integration/orderTransaction-integration/find_order_transaction_by_order_id.feature
  bank-service/src/test/resources/features/integration/orderTransaction-integration/find_order_transactions_by_account_number.feature
  bank-service/src/test/resources/features/integration/transaction-integration/deposit_withdrawal_transaction.feature
  bank-service/src/test/resources/features/integration/transaction-integration/transfer_funds.feature
Labels: lgtm, approved, size/XXL

#352 dummy commit to test test-coverage
  bank-service/pom.xml
Labels: lgtm, approved, size/XS

#356 bugfix
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
Labels: lgtm, approved, size/XS

#360 uri encode zbog space-a
  bank-service/src/main/java/rs/edu/raf/BankService/controller/AccountController.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/StockServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
  bank-service/src/test/java/rs/edu/raf/BankService/e2e/account/AccountControllerSteps.java
  otc-service/src/main/java/rs/edu/raf/OTCService/bootstrap/BootstrapData.java
  otc-service/src/main/java/rs/edu/raf/OTCService/controllers/ContractController.java
  otc-service/src/main/java/rs/edu/raf/OTCService/service/impl/ContractServiceImpl.java
  otc-service/src/test/java/rs/edu/raf/OTCService/integration/contracts/ContractsServiceTestsSteps.java
  otc-service/src/test/java/rs/edu/raf/OTCService/integration/contracts/generators/JwtConstant.java
  otc-service/src/test/java/rs/edu/raf/OTCService/integration/contracts/generators/JwtTokenGenerator.java
  stock-service/src/main/java/rs/edu/raf/StockService/controllers/ExchangeController.java
  stock-service/src/test/java/rs/edu/raf/StockService/e2e/exchangecontroller/ExchangeControllerTestsSteps.java
  stock-service/src/test/java/rs/edu/raf/StockService/e2e/optioncontroller/OptionControllerTestsSteps.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/ExchangeControllerTests.java
  stock-service/src/test/resources/features/e2e/optioncontroller/OptionController.feature
Labels: size/L, lgtm, approved

#359 #315
  stock-service/src/main/java/rs/edu/raf/StockService/controllers/SecuritiesController.java
  stock-service/src/main/java/rs/edu/raf/StockService/data/dto/SecuritiesDto.java
  stock-service/src/main/java/rs/edu/raf/StockService/mapper/SecuritiesMapper.java
  stock-service/src/main/java/rs/edu/raf/StockService/services/OptionService.java
  stock-service/src/main/java/rs/edu/raf/StockService/services/SecuritiesService.java
  stock-service/src/main/java/rs/edu/raf/StockService/services/impl/OptionServiceImpl.java
  stock-service/src/main/java/rs/edu/raf/StockService/services/impl/SecuritiesServiceImpl.java
  stock-service/src/test/java/rs/edu/raf/StockService/e2e/securitiescontroller/SecuritiesControllerTests.java
  stock-service/src/test/java/rs/edu/raf/StockService/e2e/securitiescontroller/SecuritiesControllerTestsConfig.java
  stock-service/src/test/java/rs/edu/raf/StockService/e2e/securitiescontroller/SecuritiesControllerTestsSteps.java
  stock-service/src/test/java/rs/edu/raf/StockService/integration/securitiesservice/SecuritiesServiceImplSteps.java
  stock-service/src/test/java/rs/edu/raf/StockService/integration/securitiesservice/SecuritiesServiceImplTests.java
  stock-service/src/test/java/rs/edu/raf/StockService/integration/securitiesservice/SecuritiesServiceImplTestsConfig.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/OptionServiceImplTests.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/SecuritiesControllerTest.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/SecuritiesMapperTests.java
  stock-service/src/test/java/rs/edu/raf/StockService/unit/SecuritiesServiceImplTests.java
  stock-service/src/test/resources/features/e2e/securitiescontroller/SecuritiesController.feature
  stock-service/src/test/resources/features/integration/securitiesservice/SecuritiesService.feature
Labels: size/XL, lgtm, approved

#361 Sredjivanje marznih racuna i transakcija
  bank-service/src/main/java/rs/edu/raf/BankService/MarginsAccountMaintainScheduler.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/MarginsAccountController.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/MarginsTransactionController.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsAccountRequestDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsAccountResponseDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsTransactionResponseDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/entities/MarginsTransaction.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/MarginsAccountMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/MarginsTransactionMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/repository/MarginsAccountRepository.java
  bank-service/src/main/java/rs/edu/raf/BankService/repository/specification/MarginsTransactionSpecification.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/MarginsAccountService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/MarginsTransactionService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsAccountServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsTransactionServiceImpl.java
Labels: lgtm, approved, size/M

#362 idk
  bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/OrderTransactionController.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/StockDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/repository/OrderTransactionRepository.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/OrderTransactionService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/OrderTransactionServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingJob.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
  notification-service/src/main/java/rs/edu/raf/NotificationService/configuration/RabbitMQConfig.java
Labels: lgtm, approved, size/M

#363 Izmene
  bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/MarginsAccountController.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/MarginsTransactionController.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsTransactionResponseDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/entities/MarginsTransaction.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/MarginsTransactionMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/repository/MarginsAccountRepository.java
  bank-service/src/main/java/rs/edu/raf/BankService/repository/specification/MarginsTransactionSpecification.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/MarginsAccountService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/MarginsTransactionService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsAccountServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsTransactionServiceImpl.java
Labels: size/L, lgtm, approved

#364 Izmenjen Margin
  bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/MarginsAccountController.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsAccountRequestDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/MarginsTransactionResponseDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/mapper/MarginsAccountMapper.java
  bank-service/src/main/java/rs/edu/raf/BankService/repository/MarginsAccountRepository.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/MarginsAccountService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/MarginsAccountServiceImpl.java
Labels: size/L, lgtm, approved

#365 bootstrap fix za kube
  otc-service/src/main/java/rs/edu/raf/OTCService/bootstrap/BootstrapData.java
  otc-service/src/main/resources/application-dev.properties
Labels: size/S, lgtm, approved

#366 Fix za kupovinu ordea
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/AgentDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/IAMServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/OrderServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
  bank-service/src/test/java/rs/edu/raf/BankService/unit/orderTests/OrderServiceTests.java
  iam-service/src/main/java/rs/edu/raf/IAMService/controllers/UserController.java
  iam-service/src/main/java/rs/edu/raf/IAMService/services/UserService.java
  iam-service/src/main/java/rs/edu/raf/IAMService/services/impl/UserServiceImpl.java
Labels: lgtm, approved, size/M

#368 bootstrap agen
  bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
Labels: size/S, lgtm, approved

#370 quick* fix
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
Labels: size/S, lgtm, approved

#371 OTC Service - trgovina izmedju banaka
  bank-service/src/test/java/rs/edu/raf/BankService/unit/transferTransaction/TransferServiceTests.java
  otc-service/src/main/java/rs/edu/raf/OTCService/bootstrap/BootstrapData.java
  otc-service/src/main/java/rs/edu/raf/OTCService/controllers/BankOtcController.java
  otc-service/src/main/java/rs/edu/raf/OTCService/data/dto/testing/FrontendOfferDto.java
  otc-service/src/main/java/rs/edu/raf/OTCService/data/dto/testing/MyOfferDto.java
  otc-service/src/main/java/rs/edu/raf/OTCService/data/dto/testing/MyStockDto.java
  otc-service/src/main/java/rs/edu/raf/OTCService/data/dto/testing/OfferDto.java
  otc-service/src/main/java/rs/edu/raf/OTCService/data/entity/listing/BankOTCStock.java
  otc-service/src/main/java/rs/edu/raf/OTCService/data/entity/listing/MyStock.java
  otc-service/src/main/java/rs/edu/raf/OTCService/data/entity/offer/MyOffer.java
  otc-service/src/main/java/rs/edu/raf/OTCService/data/entity/offer/Offer.java
  otc-service/src/main/java/rs/edu/raf/OTCService/data/entity/offer/OfferStatus.java
  otc-service/src/main/java/rs/edu/raf/OTCService/repositories/BankOTCStockRepository.java
  otc-service/src/main/java/rs/edu/raf/OTCService/repositories/MyOfferRepository.java
  otc-service/src/main/java/rs/edu/raf/OTCService/repositories/MyStockRepository.java
  otc-service/src/main/java/rs/edu/raf/OTCService/repositories/OfferRepository.java
  otc-service/src/main/java/rs/edu/raf/OTCService/service/test/BankOtcService.java
  otc-service/src/test/java/rs/edu/raf/OTCService/OtcServiceApplicationTests.java
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/contracts/ContractsE2ETests.java
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/contracts/ContractsE2ETestsConfig.java
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/contracts/ContractsE2ETestsState.java
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/contracts/ContractsE2ETestsSteps.java
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/generators/JwtTokenGenerator.java
  otc-service/src/test/java/rs/edu/raf/OTCService/integration/contracts/ContractsServiceIntegrationTests.java
  otc-service/src/test/java/rs/edu/raf/OTCService/integration/contracts/ContractsServiceIntegrationTestsConfig.java
  otc-service/src/test/java/rs/edu/raf/OTCService/integration/contracts/ContractsServiceTestsSteps.java
  otc-service/src/test/java/rs/edu/raf/OTCService/integration/contracts/generators/JwtConstant.java
  otc-service/src/test/java/rs/edu/raf/OTCService/integration/contracts/generators/JwtTokenGenerator.java
  otc-service/src/test/resources/features/e2e/contracts/ApproveContracts.feature
  otc-service/src/test/resources/features/e2e/contracts/DenyContracts.feature
  otc-service/src/test/resources/features/integration/contracts/ContractsApproved.feature
  otc-service/src/test/resources/features/integration/contracts/CreateContracts.feature
  otc-service/src/test/resources/features/integration/contracts/GetContracts.feature
Labels: lgtm, approved, size/XXL

#372 OTC Service - trgovina izmedju banaka
  otc-service/src/main/java/rs/edu/raf/OTCService/configuration/SpringSecurityConfig.java
Labels: lgtm, approved, size/XS

#373 Changed SpringSecurityConfig in otc service
  bank-service/src/test/java/rs/edu/raf/BankService/integration/credit/CreditStepsDefinition.java
  bank-service/src/test/resources/features/integration/credit-integration/creditFeatures.feature
  otc-service/src/main/java/rs/edu/raf/OTCService/configuration/SpringSecurityConfig.java
Labels: lgtm, approved, size/M

#374 otc changes
  otc-service/src/main/java/rs/edu/raf/OTCService/bootstrap/BootstrapData.java
Labels: lgtm, approved, size/XS

#380 Dodate transakcije u otc
  bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/OtcBankTransactionController.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/SecuritiesOwnershipsController.java
  bank-service/src/main/java/rs/edu/raf/BankService/data/dto/OtcOfferDto.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/OtcBankTransactionService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/SecuritiesOwnershipService.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/OtcBankTransactionServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/SecuritiesOwnershipServiceImpl.java
  otc-service/src/main/java/rs/edu/raf/OTCService/data/dto/SecurityOwnershipDto.java
  otc-service/src/main/java/rs/edu/raf/OTCService/service/BankService.java
  otc-service/src/main/java/rs/edu/raf/OTCService/service/impl/BankServiceImpl.java
  otc-service/src/main/java/rs/edu/raf/OTCService/service/test/BankOtcService.java
Labels: size/L, lgtm, approved

#381 boottrapc fix i avg price u ugovere
  bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
  bank-service/src/main/java/rs/edu/raf/BankService/controller/TransferTransactionController.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  iam-service/src/main/java/rs/edu/raf/IAMService/bootstrap/BootstrapDevData.java
  otc-service/src/main/java/rs/edu/raf/OTCService/bootstrap/BootstrapData.java
  otc-service/src/main/java/rs/edu/raf/OTCService/service/impl/BankServiceImpl.java
  otc-service/src/main/java/rs/edu/raf/OTCService/service/impl/ContractServiceImpl.java
Labels: lgtm, approved, size/M

#382 Dodata mal promena u bootstrap u bank-service-u
  bank-service/src/main/java/rs/edu/raf/BankService/bootstrap/BootstrapDevData.java
Labels: lgtm, approved, size/XS

#384 contract e2e test
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/buyingAndSellingOrders/BuyingAndSellingOrdersJwtConst.java
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/buyingAndSellingOrders/BuyingAndSellingOrdersSteps.java
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/buyingAndSellingOrders/BuyingAndSellingOrdersTests.java
  otc-service/src/test/java/rs/edu/raf/OTCService/e2e/buyingAndSellingOrders/BuyingAndSellingOrdersTestsConfigTest.java
  otc-service/src/test/java/rs/edu/raf/OTCService/generator/JwtTokenGenerator.java
  otc-service/src/test/resources/features/e2e/buyingAndSellingOrders/buyingAndSellingOrdersFeatures.feature
Labels: size/L, lgtm, approved

#385 profit
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
Labels: size/S, lgtm, approved

#386 profit fix
  bank-service/src/main/java/rs/edu/raf/BankService/service/impl/TransactionServiceImpl.java
  bank-service/src/main/java/rs/edu/raf/BankService/service/tradingSimulation/TradingSimulation.java
Labels: lgtm, approved, size/XS
